apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cold-pvc
  namespace: database
spec:
  storageClassName: nas-nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
